version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  secondary-artifacts:
    artifact1:
      files:
        - '**/*'
      base-directory: 'target/application'    
    artifact2:
      files:
        - target/site/pmd.html
      name: secondary-artifact-name-2
